import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactCompiler: true,
  // Turbopack configuration is handled automatically in Next.js 16
  // Optimize for production
  compress: true,
  poweredByHeader: false,
  // Enable static optimization
  trailingSlash: false,
  // Image optimization
  images: {
    formats: ['image/webp', 'image/avif'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
  },
  async headers() {
    const securityHeaders = [
      {
        key: 'Content-Security-Policy',
        value:
          [
            "default-src 'self'",
            "base-uri 'self'",
            "img-src 'self' data: https:",
            "font-src 'self' data:",
            // Allow inline JSON-LD and Next's runtime; include Clarity + GA + Meta Pixel scripts
            "script-src 'self' 'unsafe-inline' https://www.clarity.ms https://scripts.clarity.ms https://*.clarity.ms https://www.googletagmanager.com https://*.googletagmanager.com https://www.google-analytics.com https://*.google-analytics.com https://connect.facebook.net",
            // Allow Tailwind styles and any inline styles generated by components
            "style-src 'self' 'unsafe-inline'",
            // Microsoft Clarity outbound connections
            "connect-src 'self' https://www.clarity.ms https://*.clarity.ms https://www.googletagmanager.com https://*.googletagmanager.com https://www.google-analytics.com https://*.google-analytics.com https://connect.facebook.net",
            "frame-ancestors 'self'",
            "form-action 'self'",
            "object-src 'none'",
            // Auto-upgrade any http content when served over https
            'upgrade-insecure-requests',
          ].join('; '),
      },
      { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
      { key: 'X-Content-Type-Options', value: 'nosniff' },
      { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
      { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
      // HSTS (effective only on HTTPS)
      { key: 'Strict-Transport-Security', value: 'max-age=31536000; includeSubDomains; preload' },
    ];

    return [
      {
        // Apply to all routes
        source: '/(.*)',
        headers: securityHeaders,
      },
    ];
  },
  async redirects() {
    return [
      {
        source: '/residential-cleaning',
        destination: '/house-cleaning',
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
